[sinks.logflare]
  type = "http"
  inputs = ["log_json"]
  uri = "https://api.logflare.app/logs/vector?api_key=${LOGFLARE_API_KEY}&source=${LOGFLARE_SOURCE_TOKEN}"
  encoding.codec = "json"
  compression = "none"

[sinks.logflare_metrics]
  type = "http"
  inputs = ["fly_log_metrics"]
  uri = "https://api.logflare.app/logs/vector?api_key=${LOGFLARE_API_KEY}&source=${LOGFLARE_METRICS_SOURCE_TOKEN}"
  encoding.codec = "json"
  compression = "none"